### ISSUE TITLE
идея для PRO (платной) версии - корзина заказов

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#1]
Так как данным модулем можно легко создавать отдельные формы для предзаказа чего-угодно из краткой или полных новостей (с передачей названия страницы и содержимого доп-поля цена) то логичным будет предложить реализацию некой промежуточной корзины.

суть такая:

можно добавлять несколько разных товаров (кнопка предзаказа на разных страницах) а отправка письма администрации сайта будет происходить только из мини-корзины с добавленными заказами.

**Comment by pafnuty** [comment]
Корзину нжно делать другими средствами всё же.
