### ISSUE TITLE
не могу запустить модуль

### ISSUE THREAD

**Issue by OlegVahrushev** [dle-modules/DLE-UniForm#108]
# Описание ошибки: не могу запустить модуль

## Конфиг шаблона:

```
templateFolder = inline
// nocache = y
// debug = y
required = textarea, email
// hidden = newsid,user
sendmail = y
emails = mail@mail.ru, mail2@mail.ru
```

## Код используемого шаблона:
<!DOCTYPE html>
<html>
<head>
	{headers}
	<meta content="width=device-width, initial-scale=1" name="viewport">
	<link href="{THEME}/img/favicon.png" rel="shortcut icon" type="image/x-icon">
	<link href="{THEME}/css/reset.css" rel="stylesheet">
	<link href="{THEME}/css/animate.css" rel="stylesheet">
	<link href="{THEME}/css/bootstrap.min.css" rel="stylesheet">
	<link href="{THEME}/css/font-awesome.min.css" rel="stylesheet">
	<link href="{THEME}/css/owl.carousel.css" rel="stylesheet">
	<link href="{THEME}/css/nivo-slider.css" rel="stylesheet">
	<link href="{THEME}/css/style.css" rel="stylesheet">
	<link href="{THEME}/css/responsive.css" rel="stylesheet">

    

<link rel="stylesheet" href="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/css/uniform.css&amp;200" />
 

<script src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/js/jquery.magnificpopup.min.js,{THEME}/uniform/js/jquery.ladda.min.js,{THEME}/uniform/js/jquery.form.min.js,{THEME}/uniform/js/uniform.js&amp;200"></script>
    
    
<link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
 
</head>
<body>

<header id="sticker">
	{include file="modules/header.tpl"}
	{**}
	<div class="main-menu-area hidden-xs">
		<div class="container">
			<div class="menu-position">
				<div class="row">
					<div class="col-md-3 col-sm-2">
						
						<div class="logo">
							<a href="/">
								<img src="{THEME}/img/logo.png" alt="">
							</a>
						</div>
					</div>
					<div class="col-md-9 col-sm-10 static">
						<div class="main-menu">
							<nav>
								<ul>
									<li [aviable=main]class="active-on"[/aviable]><a href="/">Главная</a> </li>
									<li [static=about]class="active-on"[/static]><a href="/about.html">О нас</a></li>
								
									<li [category={include file="modules/cat-id/blog-id.tpl"}]class="active-on"[/category]><a href="/incident/">Блог</a></li>
									<li class="has-sub [category={include file="modules/cat-id/shop-id.tpl"}]active-on[/category]">
										<a href="/shop/">Каталог изделий<i class="fa fa-angle-down"></i></a>
										{include file="modules/menu/shop.tpl"}
									</li>
									<li [aviable=feedback]class="active-on"[/aviable]><a href="/index.php?do=feedback">Контакты</a></li>
								</ul>
							</nav>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{**}
	<div class="mobile-menu-area hidden-lg hidden-md hidden-sm">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					
					<div class="logo">
						<a href="/">
							<img src="{THEME}/img/logo-dark.png" alt="" vidth="128px;">
						</a>
					</div>
					<div class="mobile-menu">
						<nav style="display: block;">
							<ul>
								<li><a href="/">Главная</a> </li>
								<li><a href="/about.html">О нас</a></li>
								<li>
									<a href="/services/">Услуги</a>
									{include file="modules/menu/services.tpl"}
								</li>
								<li><a href="/blog/">Новости</a></li>
								<li>
									<a href="/shop/">Магазин</a>
									{include file="modules/menu/shop.tpl"}
								</li>
								<li><a href="/index.php?do=feedback">Контакты</a></li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

{**}
[not-aviable=main]
<div style="padding-top: 50px;">   </div>
	
	
	[not-aviable=static|feedback]
		<div class="section-padding">
			<div class="container">
				<div class="row">
					{content}
					{info}
				</div>
			</div>
		</div>
	[/not-aviable]
	
	[aviable=static|feedback]
		{content}
	[/aviable]
[/not-aviable]

{**}
[aviable=main]

	{*  *}
	{include file="modules/parts-main/slider.tpl"}
    
    	{*  *}
	<div class="shop-area section-padding">
		<div class="container">
			
			<div class="shop-tab-area">
				<ul class="shop-tab" role="tablist">
					<li class="active" role="presentation">
						<a aria-controls="tab1" data-toggle="tab" href="#tab1" role="tab">Новые изделия</a>
					</li>
					<li role="presentation">
						<a aria-controls="tab2" data-toggle="tab" href="#tab2" role="tab">Популярные изделия</a>
					</li>
					<li role="presentation">
						<a aria-controls="tab3" data-toggle="tab" href="#tab3" role="tab">Самые продаваемые</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade in active" id="tab1" role="tabpanel">
						<div class="row">
							{custom category="{include file="modules/cat-id/shop-id.tpl"}" template="modules/functions/shop" navigation="no" from="0" limit="8" cache="no" order="data"}
						</div>
					</div>
					<div class="tab-pane fade" id="tab2" role="tabpanel">
						<div class="row">
							{custom category="{include file="modules/cat-id/shop-id.tpl"}" template="modules/functions/shop" navigation="no" from="0" limit="8" cache="no" order="reads"}
						</div>
					</div>
					<div class="tab-pane fade" id="tab3" role="tabpanel">
						<div class="row">
							{custom category="{include file="modules/cat-id/shop-id.tpl"}" template="modules/functions/shop" navigation="no" from="0" limit="8" cache="no" order="rand"}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    
	{*  *}
	{include file="modules/parts-main/features.tpl"}
    
    
	{*  *}
	{include file="modules/parts-main/about.tpl"}
    {include file="modules/parts-main/about2.tpl"}

	{*  *}
	{include file="modules/parts-main/features2.tpl"}
    {include file="modules/parts-main/about3.tpl"}
    {include file="modules/parts-main/features4.tpl"}
	{*  *}
	<div class="blog-area section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-heading text-center">
						<h2><span>Наш </span>блог</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="blog-slider owl-preview-2">
					{custom category="{include file="modules/cat-id/blog-id.tpl"}" template="modules/functions/blog" navigation="no" from="0" limit="6" cache="no" order="data"}
				</div>
			</div>
		</div>
	</div>

	
[/aviable]

{**}
<div class="quick-book-area">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="book-now">
					<div class="display-table">
						<div class="display-table-cell">
							<div class="book-now-title">
								<h2>ЗАКАЖИТЕ ОБРАТНЫЙ ЗВОНОК</h2>
								
                                <span class="uf-btn" 
	  data-uniform='{"formConfig": "feedback"}'
>
 Обратная связь
</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{**}
{include file="modules/footer.tpl"}

{jsfiles}
<script type="text/javascript" src="/engine/classes/min/index.php?f={THEME}/js/modernizr-2.8.3.min.js,{THEME}/js/bootstrap.min.js,{THEME}/js/jquery.meanmenu.js,{THEME}/js/jquery.scrollUp.min.js,{THEME}/js/owl.carousel.min.js,{THEME}/js/jquery.nivo.slider.js,{THEME}/js/home.js,{THEME}/js/main.js&amp;7"></script>

{AJAX}
</body>
</html>
```
Код шаблона
```

**Comment by pafnuty** [comment]
@OlegVahrushev судя по всему вы вместо шаблона модуля используете шаблон сайта.

**Comment by OlegVahrushev** [comment]
Подключил скрипт в конце шаблона и всё заработало)
