### ISSUE TITLE
Форма не отправляется.

### ISSUE THREAD

**Issue by OlegVahrushev** [dle-modules/DLE-UniForm#109]
---
@pafnuty не забудь посмотреть этот тиккет :ticket:
Павел, день добрый! Уже не первый раз ставлю ваш модуль uniform, очень им доволен! Бывало я сам тупил при установке и не сходу он работал. ))
Но сейчас не могу понять в чём причина. Скорее всего проблема снова во мне, но не могу заставить модуль работать.
Заполняю все поля нажимаю отправить и всё... На кнопке отправить крутится спинер и ничего не происходит.
Картинку взял с вашего сайта для примера.
![1431250752_05](https://user-images.githubusercontent.com/85866487/156168343-9ba81647-f661-4ca9-ac24-a7f807bb968b.png)

**Comment by tcse** [comment]
Для DLE 15,1 проблема решается следующими правками:

Для UNIFORM 1

1. Открыть файл www/engine/modules/uniform/uniform.php 

Найти строку:

// Если данные передаются постом — надо бы их обработать
require_once ENGINE_DIR . '/classes/parse.class.php';
$parse = new ParseFilter();

И ПЕРЕД ней вставить:

include_once (DLEPlugins::Check(ENGINE_DIR . '/classes/htmlpurifier/HTMLPurifier.standalone.php'));


ДЛЯ UNIFORM 2.0


1. Открыть файл www/engine/modules/uniform/uniform.php 

Найти строку:

require_once (DLEPlugins::Check(ENGINE_DIR . '/classes/parse.class.php')); 

И ПЕРЕД ней вставить:

include_once (DLEPlugins::Check(ENGINE_DIR . '/classes/htmlpurifier/HTMLPurifier.standalone.php'));

**Comment by OlegVahrushev** [comment]
Благодарю! Всё заработало. Версия DLE 15.1, версия модуля 2.0
