### ISSUE TITLE
отправка писем в text/plain

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#11]
Возможно ли реализовать принудительный выбор типа сообщения:

1. только текст

2. только html 

сейчас при отправке только текста, все равно происходит дублирование сообщения в html 

Возможно, что это связано с mail классом в самом DLE...

**Comment by tcse** [comment]
в стандартном классе от DLE есть такая строка

if( $this->html_mail ) {
			$this->mail->msgHTML($message);
		} else {
			$this->mail->Body = $message;
		}


если не ошибаюсь именно она отвечает за конвертацию письма в html ?

**Comment by pafnuty** [comment]
[Вот тут](https://github.com/dle-modules/DLE-UniForm/blob/master/upload/engine/modules/uniform/sendmail.php#L82) вторым параметром нужно прописать `false`

в следующей версии сделаю настройку.

**Comment by pafnuty** [comment]
И [вот тут](https://github.com/dle-modules/DLE-UniForm/blob/master/upload/engine/modules/uniform/sendmail.php#L38) нужно подправить. точнее закомментировать строку.

**Comment by pafnuty** [comment]
Реализовано https://github.com/dle-modules/DLE-UniForm/commit/46b6579e3578f468647514a1e7c91cb007f9deab
