### ISSUE TITLE
[BUG] не підтримує декілька шаблонів на сайті.

### ISSUE THREAD

**Issue by serjiomati** [dle-modules/DLE-UniForm#111]
# Описание ошибки:

## Конфиг шаблона:

Стандарт

**Comment by tcse** [comment]
Это известный баг.В стандартном шаблоне сайта по умолчанию, который вы используете в папку /templates/{theme}/uniform/ пропишите клпию вашего шаблона формы.Аналогично и для смартфон шаблона.Тогда все будет работать.
-------- Исходное сообщение --------От: serjiomati ***@***.***> Дата: 11.09.2022  11:51  (GMT+03:00) Кому: dle-modules/DLE-UniForm ***@***.***> Копия: Subscribed ***@***.***> Тема: [dle-modules/DLE-UniForm] [BUG] не підтримує декілька шаблонів на сайті. (Issue #111) 
Описание ошибки:
При каких условиях воспроизводится ошибка: є стандарний шаблон там все ок, є деякі категорії де використовується інший шаблон (скажемо Tem2) то воно все рівно просить файл templates/Tem1 config file not found
Страница, на которой наблюдается ошибка:
Вносились ли модификации в движок: Так
Версия DLE:  15.2
Версия PHP:  7.4
Конфиг шаблона:
Стандарт

**Comment by serjiomati** [comment]
так і зробив, ошибка наступна зараз
` Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'HTMLPurifier_Config' not found in /home/xxadmin/web/euronet.com.ua/public_html/engine/cache/system/plugins/4fac50b01b53fc0eb4b6d4b93b5eafa7.php:62\nStack trace:\n#0 /home/xxadmin/web/euronet.com.ua/public_html/engine/modules/uniform/uniform.php(96): ParseFilter->__construct()\n#1 /home/xxadmin/web/euronet.com.ua/public_html/engine/ajax/uniform.php(99): include('/home/xxadmin/w...')\n#2 /home/xxadmin/web/euronet.com.ua/public_html/engine/ajax/controller.php(196): include_once('/home/xxadmin/w...')\n#3 {main}\n  thrown in /home/xxadmin/web/euronet.com.ua/public_html/engine/cache/system/plugins/4fac50b01b53fc0eb4b6d4b93b5eafa7.php on line 62', referer: https://euronet.com.ua/security/videosposterezhennia/`
скрін консолі.
https://prnt.sc/VaE4ydJ3uDgf

**Comment by pafnuty** [comment]
@serjiomati если не сложно, пишите, пожалуйста, по-русски или по-английски, я в общих чертах могу прочитать украинский или белорусский язык, но боюсь суть не уловлю, а переводчик какую-то дичь вечно выдаёт...

Решение проблемы описано тут: https://github.com/dle-modules/DLE-UniForm/issues/107
