### ISSUE TITLE
Тема письма в теге [head][/head]

### ISSUE THREAD

**Issue by chrome2** [dle-modules/DLE-UniForm#12]
Хочу сделать, чтобы пользователь сам указывал тему письма. В форме вывожу поле "Тема письма", прописываю его в email.tpl таким образом:  `[header]{field2}[/header]`  Но между этим тегом поле не обрабатывается.

**Comment by pafnuty** [comment]
@chrome2 проблема решена, https://github.com/dle-modules/DLE-UniForm/commit/fb7ba139da0cb4b27e5cf3a3a4184c0dbe3cf0fb#diff-34ae1fc9b5b6f46084274b6e25c8249cR58
