### ISSUE TITLE
Отправка от email который указал посетитель

### ISSUE THREAD

**Issue by mdwebppua** [dle-modules/DLE-UniForm#14]
**Как сделать так:**
- Есть поля:
- имя,email,примечание
- Как сделать так что бы при получении письма, писало от кого email посетителя который заполнил поле email ?

**Comment by pafnuty** [comment]
как выглядит шаблон, конфиг и шаблон email? а так же строка вызова?

**Comment by mdwebppua** [comment]
- config.tpl http://joxi.ru/1A5J985hKKDQVr
- email.tpl http://joxi.ru/Y2LDqw6hnn7dR2
- form.tpl http://joxi.ru/eAO64wLI449Qp2
- кнопка в шаблоне http://joxi.ru/52aeQw5cGGEBB2
Форма приходит все отлично. Но как сделать что бы был отправитель email который вписал посетитель?

**Comment by pafnuty** [comment]
@mdwebppua в настройках email отключено: http://joxi.ru/DrlpPqWF44OGGr ?

**Comment by mdwebppua** [comment]
Не нашел такого пункта в настройках DLE 10.6

**Comment by pafnuty** [comment]
Да, действительно.
Наверное это из-за смены класса отправки почты.
В принципе это правильно, так письмо не попадёт в спам, естественно при условии корректной настройке.

**Comment by pafnuty** [comment]
Значит при текущем раскладе никак не получится сделать без правок модуля.

**Comment by tcse** [comment]
такая ерунда с phpmail еще с 10.5 началась.
ВСЕ письма отправляют только от лица email админа указанного в админке движка.

**Comment by pafnuty** [comment]
@mdwebppua Попробуйте внести правки из этого коммита: https://github.com/dle-modules/DLE-UniForm/commit/7c5b811cf3c72c9bfd90bb1fd79d15cfdfa39da6 
Должно заработать.

**Comment by mdwebppua** [comment]
А как сделать когда посетитель не зарегистрированный вводит свой e-mail в форму и приходило к нам на почту от его e-mail письмо?

**Comment by pafnuty** [comment]
Приложите код шаблонов модуля.

**Comment by mdwebppua** [comment]
Они више в скринах.

**Comment by pafnuty** [comment]
Что выдают логи, и конкретно поле `Reply-To`?

**Comment by mdwebppua** [comment]
А где это посмотреть? я вообще не понимаю куда копать, но знаю что что то накосячил ((

**Comment by pafnuty** [comment]
Если у почтового сервера есть логи - можно посмотреть в логах, если нет - можно в gmail посмотреть http://joxi.ru/BA0Re7YuBpx5Jm

**Comment by mdwebppua** [comment]
Это оно http://joxi.ru/Y2LDqw6hnERRG2 ?

**Comment by pafnuty** [comment]
Да, оно. И судя по http://joxi.ru/v29NeEYSGpvgYA всё формируется корректно.

**Comment by mdwebppua** [comment]
Но сообщение приходит от info@ua-cinema.com.ua а не от dima@mail.ru

**Comment by pafnuty** [comment]
Так и должно быть. Иначе почтовик будет расценивать письмо как спам.

**Comment by mdwebppua** [comment]
у меня есть сторонний php файл который отправляет от имени отправителя и не попадает в спам, думал у вас тоже можно так реализовать. Зачем тогда мне письмо от самого себя)

**Comment by pafnuty** [comment]
Ну так письмо отправляется средствами DLE, а не средствами модуля.
Просто замените класс отправки email на собственный или старый, от 10.4.
