### ISSUE TITLE
Указание тайтла и ссылки страницы откуда было отправлено письмо

### ISSUE THREAD

**Issue by DanielDefo** [dle-modules/DLE-UniForm#16]
Т.е. если пользователь отправил сообщение не с главной страницы сайта а при просмотре новости, то выдергивать заноловок этой новости и ссылку на нее и отправлять на почту админу.

Желательно сделать как опцию... Будет более адаптивный модуль...

**Comment by pafnuty** [comment]
@DanielDefo  На данный момент есть тег `{current_page}` который выводит url страницы, с которой пользователь отправил сообщение.
Данные о новости пока в работе.

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-UniForm/commit/c0cb1cce2d28646a4012ac62402f1b597636391a
