### ISSUE TITLE
Вывод данных дополнительных полей из профиля юзера

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#22]
В шаблоне userinfo.tpl все пользовательские доп-поля выводятся тегом {xfields} 

Возможно ли передавать содержимое этих доп-полей в uniform?

так как теги

[user_email]{user_email}[/user_email] 
[user_foto]{user_foto}[/user_foto] 
[user_land]{user_land}[/user_land]

не покрывают все возможные сценарии данных о посетители сайта.

**Comment by pafnuty** [comment]
Думаю можно.
