### ISSUE TITLE
Не приходят письма на почту

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#23]
CMS: DLE 10.6.
Проблема: не приходят письма при отправке.

Выходит окно об успешной отправке (Спасибо за обращение! Если оно потребует ответа — мы свяжемся с вами), но письмо на почту не приходит. Смотрел спам, чистил несколько раз кеш в админке.

В email.tpl всё указал как положено. Безрезультатно. В чем может быть проблема?

**Comment by pafnuty** [comment]
Приложите код шаблонов.

**Comment by inweid** [comment]
// -----------------
// Настройки UniForm
// -----------------

// -------------------------------------------
// Доступные параметры (значение по умолчанию)
// templateFolder — Папка с шаблонами формы формы, указывается подпапка, в папке uniform текущего шаблона сайта сайта (feedback), в которой должны лежать файлы config.tpl, form.tpl и email.tpl
// nocache        — Отключение кеширования модуля (false)
// debug          — Дебаг (false)
// required       — Обязательные поля (false)
// hidden         — Разрешенные скрытые поля (false). Такие поля передаются из data-* атрибута кнопки открытия формы
// sendmail       — Отправлять email при заполнения формы? (false)
// emails         — Адреса почты, на которые необходимо отправлять уведомление (false)
// selectFields   — Поля типа select
// checkboxFields — Поля типа checkbox
// radioFields    — Поля типа radio
// sendAsPlain    — Отправлять сообщение как простой текст
// sendToAuthor   — Отправить письмо автору новости, если есть newsId есть поле с name="newsId" и если автор разрешил получение писем с сайта.
// -------------------------------------------


templateFolder = callback
// nocache = y
// debug = y
required = phone
required = name
selectFields = calltime
sendmail = y
emails = avkacom@gmail.com

**Comment by inweid** [comment]
<span class="uf-btn" data-uf-open="/engine/ajax/uniform/uniform.php" data-uf-settings='{"formConfig": "callback"}'>Обратная связь</span>

**Comment by inweid** [comment]
остальное не трогал

**Comment by pafnuty** [comment]
Конфиг настроен, на первый взгляд верно. 
Проверьте, уходит ли вообще письмо с сервера.
Попробуйте отправить ПМ на этот email из DLE.

В будущем используйте разметку markdown для оформления кода.

**Comment by inweid** [comment]
Письма напрямую (через стандартный feedback) тоже не приходят. Значит нужно писать хостеру, я правильно понимаю?

**Comment by pafnuty** [comment]
да, скорее всего проблема в хостинге.

**Comment by inweid** [comment]
Окей, попробую разобраться. Спасибо большое.
