### ISSUE TITLE
идея: расположение папок форм и системных стилей и скриптов

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#24]
Сейчас структура папок модуля и  служебных стилей/скриптов в одной куче, что затрудняет работу с шаблонами файлов. 

Предлагаю пару вариантов для "причесывания" структуры:

вместо структуры: 

{THEME}/uniform/shab1/
{THEME}/uniform/shab2/
{THEME}/uniform/shab3/
{THEME}/uniform/css/
{THEME}/uniform/js/

**вариант 1**

{THEME}/uniform/_source/
{THEME}/uniform/_source/css/
{THEME}/uniform/_source/js/
{THEME}/uniform/shab1/
{THEME}/uniform/shab2/
{THEME}/uniform/shab3/

**вариант 2**

{THEME}/uniform/css/
{THEME}/uniform/js/
{THEME}/tpl/shab1/
{THEME}/tpl/shab2/
{THEME}/tpl/shab3/

Надеюсь из списка понятна логика.

**Comment by pafnuty** [comment]
Так ничто же не мешает переделать для конкретного проекта.
Текущее расположение — лишь пример реализации.
