### ISSUE TITLE
Маска для форм ввода телефонов

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#25]
Приветствую.
Есть ли возможность прикрепить маску для полей ввода моб. телефонов? Пробовал прикрутить сторонний скрипт, но как-то тщетно, не отображается. Вероятно, что-то с чем-то конфликтует. Не пробовали?

**Comment by pafnuty** [comment]
Попробуйте [этот](https://igorescobar.github.io/jQuery-Mask-Plugin/)

**Comment by inweid** [comment]
спасибо) попробую
