### ISSUE TITLE
Не приходят письма автору новости

### ISSUE THREAD

**Issue by slon-pr** [dle-modules/DLE-UniForm#26]
DLE 11. Версия модуля 1.2.1
У форм, обратной связи с администратором, письма приходят (feedback, callback).
У формы newsauthor, письма не приходят автору новости. У пользователя разрешено получать сообщения.
**В config.tpl:**
```
templateFolder = newsauthor
// nocache = y
// debug = y
required = textarea, email
hidden = newsId
sendmail = y
sendToAuthor = y
```

**Comment by slon-pr** [comment]
С сайта через стандартную форму приходят сообщения пользователю.

**Comment by pafnuty** [comment]
В модуль передаётся [id новости](https://github.com/dle-modules/DLE-UniForm/blob/master/templates/Default/uniform/newsauthor/form.tpl#L6)?

**Comment by slon-pr** [comment]
Нет, не передавалось. Я взял код с примера на сайте вашем. Думал он готовый уже, для обратной связи с автором.
Поставил тот, который по ссылке выше. Все работает теперь. Спасибо!

**Comment by slon-pr** [comment]
Хотя на сайте у вас в примере тоже прописан {news-id}
