### ISSUE TITLE
Как подключить jQuery к Uniform?

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#27]
Привет!
Uniform окна появляются аяксом и на них почему-то не действует сторонний jQuery код, который подгружается посредством .ready (т.е. после того как сформируется DOM). Как быть?

**Comment by pafnuty** [comment]
После [этой](https://github.com/dle-modules/DLE-UniForm/blob/master/templates/Default/uniform/js/uniform.js#L95) строки пропишите код, который вы пишите внутри ready.
