### ISSUE TITLE
Отправка письма на введенный {email}

### ISSUE THREAD

**Issue by keedhost** [dle-modules/DLE-UniForm#28]
Здравствуйте. Как сделать, чтобы при нажатии на кнопку отправки копия письма отправлялась также в адрес, введенный в форме?
К примеру, `config.tpl ` введено следущее:
`emails = h0st@ukr.net,{email}`

Но на {email} не приходит. Не подскажете, в чем проблема?

**Comment by pafnuty** [comment]
Добрый вечер.
Такой функционал не предусмотрен и в принципе я не планировал делать что-то подобное. 
Всё же модуль предназначен не для email рассылок :smile: l

**Comment by tcse** [comment]
Павел,  email рассылок тут совсем не при чем.

Идея со спец-тегом {email} или {email-sender} очень правильная, для нее есть как-миниму одно, но очень важное применение:

- Допустим использование Uniform в качестве формы предзаказа. Возможность при формлении автоматически получать копию письма отправленного на сайт очень правильная.
- Или форма псевдо-тикета (копия отправителю необходима).

При этом, стоит учесть ряд моментов:

- **config.tpl** должен получить спец-тег для автоматической подставки адреса отправителя, допустим _{email-sender}_
- **form.tpl** нужен чекбокс "отправить копию запроса на мой email"
- **email.tpl** новые теги для разделения текста, отдельно для получателя и отдельно для отправителя.
например, 
**[email-sender]** текст для отправителя сообщения, если в форме был указан чекбокс отправить копию запроса на мой email **[/email-sender]**

**[email-to]** текст для получателя формы **[/email-to]**

При таком раскладе, можно будет реализовать большее количество вариантов применения модуля.

**Comment by pafnuty** [comment]
@tcse ок, уговорили :)

**Comment by tcse** [comment]
эх... как там дела с новыми фичами? Может еже начнешь собирать денег на реализацию этих фичей?
Скажи сколько надо заслать.

**Comment by pafnuty** [comment]
@tcse не в деньгах дело, а в нехватке времени, к сожалению 😢
