### ISSUE TITLE
Небольшая проблемка

### ISSUE THREAD

**Issue by crigma** [dle-modules/DLE-UniForm#29]
Помогите пожалуйста чет не могу настроить,все работает но только одно но,сообщение не доходит на почту в конфиг.тпл 4 емайлы добавил ни на одном не доходит

**Comment by pafnuty** [comment]
приложите код конфига и адрес страницы, на которой лежит форма.

**Comment by crigma** [comment]
http://vorec.net/film/14323-beshenyenbsp2015.html


`// -----------------
// Настройки UniForm
// -----------------

// -------------------------------------------
// Доступные параметры (значение по умолчанию)
// templateFolder — Папка с шаблонами формы формы, указывается подпапка, в папке uniform текущего шаблона сайта сайта (feedback), в которой должны лежать файлы config.tpl, form.tpl и email.tpl
// nocache        — Отключение кеширования модуля (false)
// debug          — Дебаг (false)
// required       — Обязательные поля (false)
// hidden         — Разрешенные скрытые поля (false). Такие поля передаются из data-* атрибута кнопки открытия формы
// sendmail       — Отправлять email при заполнения формы? (false)
// emails         — Адреса почты, на которые необходимо отправлять уведомление (false)
// selectFields   — Поля типа select
// checkboxFields — Поля типа checkbox
// radioFields    — Поля типа radio
// sendAsPlain    — Отправлять сообщение как простой текст
// sendToAuthor   — Отправить письмо автору новости, если есть newsId есть поле с name="newsId" и если автор разрешил получение писем с сайта.
// -------------------------------------------


templateFolder = feedback
// nocache = y
// debug = y
required = textarea, email
// hidden = newsid,user
sendmail = y
// emails = crigma1@mail.ru, support@vorec.net,crigma@mail.ru,marcfruit@mail.ru,`

**Comment by pafnuty** [comment]
Уберите комментарий перед
emails 
чтобы получилось 
```
emails = crigma1@mail.ru, support@vorec.net,crigma@mail.ru,marcfruit@mail.ru
```

**Comment by crigma** [comment]
огромный поклон,спасибо
