### ISSUE TITLE
Форма обратной связи с автором новости

### ISSUE THREAD

**Issue by slon-pr** [dle-modules/DLE-UniForm#3]
Суть такова.
Есть автопортал, где пользователи размещают объявление о продаже авто.
При просмотре полной новости, сделать возможность посетителям и ГОСТЯМ отвтетить на почту продавцу. Например, заинтересовало меня объявление, я пишу через форму сообщение продавцу, где я указываю свое имя, почту, телефон (как дополнение) и сам текст. Это сообщение приходит продавцу на его почту.

Думаю суть понятна. На подобных сайтах часто можно встретить такую функцию. В принципе, этот функционал подойдет для любой тематики: доска объявлений, справочник города  и т.п..

**Comment by tcse** [comment]
получается, что нужна переменная для вывода email автора поста?
в config.tpl 

emails = vasya@pupkin.ru, {post-autor-mail}

типа того?

хорошая тема - контролировать (дублировать) все предложения на своей площадке (вроде как частные) отправкой на специальное мыло администрации сайта :)

**Comment by pafnuty** [comment]
@tcse нужна переменная, которая будет передавать информацию из формы в обработчик email-сообщения.

@slon-pr суть ясна, принято в работу.

**Comment by slon-pr** [comment]
Спасибо! Пафнутий, прочитал на вашем блоге, что может добавите вывод формы без модального окна? Например, в футере я хочу форму обратной связи установить (как на шаблонах WP обычно делают). Либо для лединг страниц. Там же обычно форма на странице сразу отображается. Ну и хотелось родную форму обратной связи заменить на вашу. 

В общем, было замечательно, если можно будет выводить форму без модальных окон.

**Comment by pafnuty** [comment]
@slon-pr https://github.com/pafnuty/DLE-UniForm/issues/2 уже давно в планах.
А вообще рекомендую нажать кнопочку "Watch" вверху, тогда обо всех изменениях  этом репозитории будете сразу получать уведомления на email, очень удобно следить за развитием :smile:

**Comment by slon-pr** [comment]
Понятно, нажал ) Не пользовался этим сервисом просто )

**Comment by slon-pr** [comment]
А, можно добавить еще адрес страницы, откуда было отправленно письмо? Чтобы в письме был указан адрес новости? Ну и заголовок, если возможно конечно...

**Comment by pafnuty** [comment]
Через js можно подсунуть в скрытое поле.
22.05.2015 17:13 пользователь "slon-pr" <notifications@github.com> написал:

**Comment by tcse** [comment]
Через js можно подсунуть в скрытое поле.

Паша, ты тут один такой умный :)

я бы тоже сильно был бы рад готовому JS коду который бы передавал в скрытое поле URL и Заголовок статьи. 

Будет такая возможность - чиркани строки такого файлика пожалуйста.

**Comment by pafnuty** [comment]
@tcse 
Как то так.
```javascript
$(document).on('submit', '[data-uf-form]', function (e) {
	e.preventDefault();
	var url = location,
		$hiddenField = $('.hiddenField');
	$hiddenField.val(url);
})
```

**Comment by pafnuty** [comment]
Готово https://github.com/dle-modules/DLE-UniForm/commit/c0cb1cce2d28646a4012ac62402f1b597636391a

**Comment by dollar1981** [comment]
Еще вопрос: Вставил форму не в модальное окно, а вывел прямо на странице сайта, после отправки появляется сообщение об успешной отправке и все! То есть чтобы форма снова появилась надо перезагружать страницу, а можно как то сделать автоматом? Чтобы после успешной отправке, форма сама перезагружалась? И что необходимо для этого сделать?
