### ISSUE TITLE
неправильный вызов формы 

### ISSUE THREAD

**Issue by geniusnet404** [dle-modules/DLE-UniForm#32]
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

есть два шаблона: rus и eng 

главни шаблоне rus

есть форма на русском и на английском
rus\uniform\feedback и eng\uniform\feedback 

когда открываю форму на английском шаблоне выводится форма из русского шаблона

**Comment by geniusnet404** [comment]
как исправить не скажешь ? :)

**Comment by pafnuty** [comment]
@geniusnet404 необходимо в файле модуля воспроизвести поведение DLE по переопределению параметров конфига.

**Comment by geniusnet404** [comment]
канкрэтна что надо изменить можешь сказать ?

**Comment by pafnuty** [comment]
Можно начать с [этого файла](https://github.com/dle-modules/DLE-UniForm/blob/master/engine/modules/uniform/uniform.php), дальше по ситуации.
