### ISSUE TITLE
не появляется форма 

### ISSUE THREAD

**Issue by artsss** [dle-modules/DLE-UniForm#33]
Добрый день, сайт portal-vl.ru
нажимаю на кнопку обратной связи, страница темнеет но форма не появляется.....

сначала какое то время форма работала, но потом перестала, где накосячил не могу понять, заного уже переустанавливал несколько раз

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
![image](https://cloud.githubusercontent.com/assets/1635679/18239210/5931f9e2-734c-11e6-90db-7e52982397c1.png)
Вы похоже некорреектно вставили код в js файл.

**Comment by artsss** [comment]
а как я его мог некорректно вставить если все js файлы были в архиве который просто грузился в корень сайта

**Comment by artsss** [comment]
<script type="text/javascript" src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/js/jquery.magnificpopup.min.js,{THEME}/uniform/js/jquery.ladda.min.js,{THEME}/uniform/js/jquery.form.min.js,{THEME}/uniform/js/uniform.js&amp;01"></script>

вот с этим скриптом что то не так, без него ошибок в дебаге нету по этой форме

**Comment by artsss** [comment]
`<script type="text/javascript" src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/js/jquery.magnificpopup.min.js,{THEME}/uniform/js/jquery.ladda.min.js,{THEME}/uniform/js/jquery.form.min.js,{THEME}/uniform/js/uniform.js&amp;01"></script>`

**Comment by artsss** [comment]
проверил код, проблема была в том что почему то была уделена часть кода Ready, но отредактировав файл, ошибка в дебаге исчезла, но форма всеравно так и не появляется

**Comment by pafnuty** [comment]
Проверьте список забаненных IP, я получаю такую ошибку при попытке открыть форму: 
https://github.com/dle-modules/DLE-UniForm/blob/c8a4e4846a1b05dab7ce93ce0adb6d4b2bf83a7f/engine/ajax/uniform/uniform.php#L120

**Comment by artsss** [comment]
В бане нет ни одного IP адресса

**Comment by pafnuty** [comment]
Проверьте ещё раз корректность установки модуля, возможно файлы повреждены или неправильно перекодированы.
Так же **обязательно** проверьте его на **чистой версии DLE, в кодировке UTF-8, с шаблоном по умолчанию**.

**Comment by artsss** [comment]
Залил файлы заного на хост , все заработало, мистика) спасибо)

**Comment by tcse** [comment]
сталкивался с такой проблемой:
оказалось, что если я использовал модуль с самой первой версии (до того, как автор немного поменял порядок формирования шаблонов) то обновление до новых версий ломала отображение модального окна.

решение: удалить файлы модуля целиком и переустановить заного.
