### ISSUE TITLE
Письма попадают в папку спам

### ISSUE THREAD

**Issue by slon-pr** [dle-modules/DLE-UniForm#34]
Здравствуйте Павел.
Замечаю, что письма часто попадают в спам при отправке автору новости. Т.е, автор новости не получает письмо на свой ящик во **Входящие**.
Почта яндекс.
Есть какие нибудь предположения или рекомендации? Или с этим уже ничего не поделать? Или яндекс отправляет в спам из-за ссылок на мой сайт внутри письма (ссылка на новость автора)?

**Comment by pafnuty** [comment]
Добрый вечер!
А как почта уходит с сервера? С вашего адреса или через сторонний сервис? 
пробовали pdd.yandex.ru?

**Comment by slon-pr** [comment]
С сервера с моего сайта. Сервисы не подключал.
pdd.yandex.ru не пробовал. А что это? Подключу свой домен, а дальше где прописать его?

**Comment by pafnuty** [comment]
Дальше как обычную почту

06 сен 2016 г. 16:50 пользователь "slon-pr" <notifications@github.com>
написал:

**Comment by slon-pr** [comment]
Ну т.е. в админке dle указать эту почту?

**Comment by tcse** [comment]
Паша, это известная проблема, она НИКАК не связана с модулем.
Это параноидальные настройки хостинга.
была аналогичная проблема с Infobox.ru и Яндекс почтой.
все решилось перепиской с ТП хостинга и указанием spdf записи на сайте.

**Comment by pafnuty** [comment]
> Ну т.е. в админке dle указать эту почту?

мануалов по настройке довольно много, сейчас я не смогу точно подсказать порядоку действий, но они довольно очевидны.

**Comment by slon-pr** [comment]
Хорошо. Спасибо!
