### ISSUE TITLE
не приходят письма на почту

### ISSUE THREAD

**Issue by vladislavium** [dle-modules/DLE-UniForm#35]
Добрый день
тестирую форму, всё работает, только на почту не приходит ответ.
сайт http://30.host51.z8.ru/
спасибо
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Добрый день!
1. Проверьте конфиг, есть ли там незакомментированная строчка с адресом почты, на которую необходимо отправить email. Если всё ок, то:
2. Проверьте спам. Если там ничего нет, то: 
3. Проверьте логи почтового сервера.

**Comment by vladislavium** [comment]
спасибо за быстрый ответ.
выдержка из mailлога

Sep  6 17:33:43 stronghold sendmail[14669]: u86EXhFF014669: Authentication-Warning: stronghold.z8.ru: host51 set sender to vladislavium@gmail.com using -f
Sep  6 17:33:43 stronghold sendmail[14669]: u86EXhFF014669: from=vladislavium@gmail.com, size=1403, class=0, nrcpts=1, msgid=<0874e406dd37de1b17a22decf5271739@30.host51.z8.ru>, relay=host51@localhost
Sep  6 17:33:43 stronghold sendmail[14669]: u86EXhFF014669: to=vladislavium@gmail.com, ctladdr=vladislavium@gmail.com (30210/30210), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=31403, relay=[10.13.0.69] [10.13.0.69], dsn=5.0.0, stat=Service unavailable

**Comment by pafnuty** [comment]
А конфиг модуля провеили, что там у вас прописано?

**Comment by vladislavium** [comment]
да.
templateFolder = feedback
// nocache = y
// debug = y
required = textarea, email
// hidden = newsid,user
sendmail = y
emails = vladislavium@gmail.com

**Comment by vladislavium** [comment]
есть подозрение, что, что то не то с настройками php mail () у хостинга.
петерхост

**Comment by pafnuty** [comment]
0/30210), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=31403, relay=[10.13.0.69] [10.13.0.69], dsn=5.0.0, **stat=Service unavailable**

возможно в этом причина.
А обычная почта с сайта ходит?
Попробуйте сделать масовую рассылку и указать  кач-ве получателя себя.

**Comment by vladislavium** [comment]
сделал отправку письма admin на мыло

вот какой результат отправки ( Could not instantiate mail function.
попробую помучать хостера. извините за беспокойство.

**Comment by vladislavium** [comment]
кстати для запуска формы мне пришлось "расчехлить" ссылки на стили и скрипты. это нормально?

было:

<link rel="stylesheet" href="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/css/uniform.css&amp;01" />
<script type="text/javascript" src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/js/jquery.magnificpopup.min.js,{THEME}/uniform/js/jquery.ladda.min.js,{THEME}/uniform/js/jquery.form.min.js,{THEME}/uniform/js/uniform.js&amp;01"></script>


стало:


<link rel="stylesheet" href="/templates/rentcar/uniform/css/uniform.css" />
<script type="text/javascript" src="/templates/rentcar/uniform/js/jquery.magnificpopup.min.js"></script>
<script type="text/javascript" src="/templates/rentcar/uniform/js/jquery.ladda.min.js"></script>
<script type="text/javascript" src="/templates/rentcar/uniform/js/jquery.form.min.js"></script>
<script type="text/javascript" src="/templates/rentcar/uniform/js/uniform.js"></script>

**Comment by vladislavium** [comment]
было

`<link rel="stylesheet" href="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/css/uniform.css&amp;01" />
<script type="text/javascript" src="/engine/classes/min/index.php?charset=utf-8&amp;f={THEME}/uniform/js/jquery.magnificpopup.min.js,{THEME}/uniform/js/jquery.ladda.min.js,{THEME}/uniform/js/jquery.form.min.js,{THEME}/uniform/js/uniform.js&amp;01"></script>`



стало

`
<link rel="stylesheet" href="/templates/rentcar/uniform/css/uniform.css" />
<script type="text/javascript" src="/templates/rentcar/uniform/js/jquery.magnificpopup.min.js"></script>
<script type="text/javascript" src="/templates/rentcar/uniform/js/jquery.ladda.min.js"></script>
<script type="text/javascript" src="/templates/rentcar/uniform/js/jquery.form.min.js"></script>
<script type="text/javascript" src="/templates/rentcar/uniform/js/uniform.js"></script>
`

**Comment by pafnuty** [comment]
Да, но я бы на вашем месте задумался над целесообразностью использования этого хостинга, вероятно там всё очень сильно урезано.
