### ISSUE TITLE
Как в модуль UniForm, в шаблон email вставить вывод дополнительного поля из профиля пользователя?

### ISSUE THREAD

**Issue by serg91100** [dle-modules/DLE-UniForm#36]
Добрый день. Подскажите, никак не разберусь. Как в модуль UniForm, в шаблон email вставить вывод дополнительного поля из профиля?
Я создал доп поле в профиле imya, fam, otch (имя, фамилия, отчество) - но запутался, как их вставить в шаблон email, чтобы на почте я видел их. Заранее спасибо.

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Внесите необходимые изменения вот в этот блок кода https://github.com/dle-modules/DLE-UniForm/blob/master/engine/modules/uniform/uniform.php#L129

**Comment by pafnuty** [comment]
#22

**Comment by serg91100** [comment]
$_POST['user_xf_imya']     = $member_id['imya'];
$_POST['user-xf-fam']     = $member_id['fam'];
$_POST['user-xf-otch']     = $member_id['otch'];

Так? Честно говоря, я не совсем понимаю как. 
В профиле я вывожу так [xfvalue_familiya]
В новостях так {user-xf-familiya} {user-xf-imya} {user-xf-otchestvo}
Буду признателен за помощь за пример хотя бы одного из дополнительного поля

**Comment by serg91100** [comment]
$_POST['user_imya'] = $member_id['xfields_imya'];
$_POST['user_fam'] = $member_id['xfields_fam'];
$_POST['user_otch'] = $member_id['xfields_otch'];
Вот так тоже делал, но все пустое...
