### ISSUE TITLE
Не приходит заявка uniform на указанный емайл.

### ISSUE THREAD

**Issue by gootzor** [dle-modules/DLE-UniForm#39]
---
Здравствуйте. Поставил модуль uniform на сайт, но при заполнении и отправки заявки, она не приходит емайл, указанный в config.tpl, в чем может быть проблема? Сайт http://otdih-v-yeiske.ru/  версия dle 11.1
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Добрый день!
Покажите содержимое config.tpl
