### ISSUE TITLE
не могу установить модуль

### ISSUE THREAD

**Issue by xxxdarkforces** [dle-modules/DLE-UniForm#42]
как запустить установщик?
инструкция от 1,2  не подходит 
The content could not be loaded.
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Рад, что вы следите за обновлениями, используйте такой url: 
```
/dle_module_install.php?module=uniform
```

**Comment by xxxdarkforces** [comment]
спасибо, но не помогло, куча ошибок синтаксиса
syntax error, unexpected '[' 
/dle_module_install.php on line 18
/dle_module_install.php on line 80
/dle_module_install.php on line 138
/dle_module_install.php on line 189

/dle_starter_installer/install.class.php on line 17
/dle_starter_installer/install.class.php on line 22
/engine/modules/uniform/install/config.php on line 14
/engine/modules/uniform/install/config.php on line 16

**Comment by pafnuty** [comment]
Обновите php хотя бы до 5.4.

13 окт 2016 г. 6:39 пользователь "xxxdarkforces" <notifications@github.com>
написал:

**Comment by xxxdarkforces** [comment]
спасибо!
