### ISSUE TITLE
Приходят просто теги: {news_autor} {news_title}

### ISSUE THREAD

**Issue by slon-pr** [dle-modules/DLE-UniForm#44]
Почему приходят на почту в письме просто теги **{news_autor}** и **{news_title}** ?
Пример: З**дравствуйте {news_autor}! и т.д.**
Шаблон newsauthor. Все настройки по умолчанию.
```
[header]
	Сообщение автору новости
[/header]
<h2 style="margin: 0; padding: 20px; color: #ffffff; background: #4b9fc5;">Новое сообщение автору новости</h2>
<p>
	Здравствуйте <b>{news_autor}</b>!
</p>
<p>
	На сайте "{site_short_title}" к вашей новости <a href="{site_http_home_url}?newsid={news_id}" target="_blank">{news_title}</a> было отправлено сообщение через форму обратной связи.
</p>
<div style="background: #fafafa; padding: 20px; color: #333333;">
	<b>Дата отправки: </b> {send_date} <br>
	<b>Email отправителя: </b> {email} <br>
	<b>Текст сообщения: </b> <br>
	{textarea}
</div>
<p>Сообщение отправлено со страницы: {current_page}</p>
<p>Вы можете связаться с автором сообщения самостоятельно по указанному email-адресу.</p>
```

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Как обстоят дела с другими шаблонами?

**Comment by slon-pr** [comment]
Остальные поля заполненные приходят.

**Comment by slon-pr** [comment]
И все таки приходят просто теги. Залил по умолчанию шаблон newsauthor. В настройках ничего не делал.
Здравствуйте **{news_autor}!**
На сайте "имя сайта отображается" к вашей новости **{news_title}** было отправлено сообщение через форму обратной связи...

**Comment by pafnuty** [comment]
Тиккет помечен как баг, как будет время - проверим и разберёмся.

**Comment by pafnuty** [comment]
на 11,2 ошибка не воспроизводится
