### ISSUE TITLE
Оттправка фото из формы на почту

### ISSUE THREAD

**Issue by Asiuswork** [dle-modules/DLE-UniForm#45]
Здравствуйте!
Не получается добиться отправки фото на почту 
http://rentmeua.com/

SMTP работает. Кнопка вызова формы стоит в футере картинкой "18+"
Текстовая инфа приходит на почту,  а фотки нет. 

На другом сайте http://prokachu.com/razmeshenie.html  поставили обычную PHP форму тоже через SMTP то фото отправляются. Но она не такая функциональная как ваша :)

Заранее спасибо за помощь!

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by Asiuswork** [comment]
Удалось исправить:

Ошибка была здесь:
Михаил (23.11.2016 18:21):
engine/modules/uniform.php строка 220
там было gfg а надо cfg

**Comment by pafnuty** [comment]
Исправлено
