### ISSUE TITLE
jQuery UI не поддерживается в модальных окнах?

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#48]
Приветствую, не удается подключить Datepicker. Есть возможность заставить jQuery UI работать в модальных окнах?

**Comment by pafnuty** [comment]
@inweid в модуле используется плагин https://github.com/dimsemenov/Magnific-Popup
пропишите нужный js код для показа datepicker в колбэк, который срабатывает после открытия модального окна
http://dimsemenov.com/plugins/magnific-popup/documentation.html#api
