### ISSUE TITLE
формат телефона для input 

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#49]
Многие клиенты спрашивают такую фичу:
поле телефон не просто текстовое - 7921-9876543
а с автоматическим форматированием (как у сервисов обратного звонка)
+7 (921) 987-65-43 

возможно ли реализовать?

вроде это - Маска ввода номера телефона 

вариант скрипта маски телефона http://smartlanding.biz/maska-vvoda-nomera-telefona.html 

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
https://igorescobar.github.io/jQuery-Mask-Plugin/
http://digitalbush.com/projects/masked-input-plugin/
это два наиболее подходящих плагина.
Как правило достаточно указать data-* атрибут


9 марта 2017 г., 13:12 пользователь Vitaly V. Chuyakov <
notifications@github.com> написал:

**Comment by tcse** [comment]
что-то не вышло у меня :(

попытался запилить вариант http://digitalbush.com/projects/masked-input-plugin/ 

вроде все просто:

вставить в main.tpl после js от uniform 
`<script type="text/javascript" src="{THEME}/uniform/js/jquery.maskedinput.js"></script>`


в конце страницы перед закрывающим /body 

вставил 

`
<script type="text/javascript" language="javascript">
	jQuery(function($){
	   $("#phone").mask("(999) 999-9999");
	});
</script>`

в шаблоне uniform в form.tpl для поля вволя телефона добавилid=phone

вышло так
`<input id="phone" class="uf-input uf-input-first [uf_error_phone]uf-input-error[/uf_error_phone]" type="text" name="phone" value="{uf_field_phone}">`

но увы, не работает :(

**Comment by VitArts** [comment]
<script type="text/javascript">
  jQuery(function($){
   $("#phone").mask("+7 (999) 999-9999");
});
</script>

Добавь в файл form.tpl

**Comment by tcse** [comment]
ну вот, совсем другое дело.

Спасибо.

**Comment by pafnuty** [comment]
> Добавь в файл form.tpl

не надо так делать. 
@tcse возьми плагин https://igorescobar.github.io/jQuery-Mask-Plugin/ и используй `data-mask="+7 (999) 999-9999"`
