### ISSUE TITLE
Выбор  получателя письма в зависимости от селекта в форме

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#50]
Возможно ли как-то реализовать тригер для отправки сообщения определенному адресату в зависимости от выбранного селекта?

допустим в файле config.tpl
указаны:

emails = user1@gmail.com, user3@gmail.com,user3@gmail.com

а в файле form.tpl 

```
<div class="uf-field">
				<div class="uf-label">
					Что интересует?
				</div>
				<div class="uf-field-input">
					<select name="calltime" class="uf-input">
						
						<option value="1_avto" [uf_select_calltime_1_avto]selected[/uf_select_calltime_1_avto]>Автомобили</option>
						<option value="2_pars" [uf_select_calltime_2_pars]selected[/uf_select_calltime_2_pars]>Запчасти</option>
						<option value="3_service" [uf_select_calltime_3_service]selected[/uf_select_calltime_3_service]>Сервис</option>
					</select>
				</div>
			</div>
```

При выборе первого селекта "Автомобили" 
письмо будет отправлено на user1@gmail.com

при выборе второго селекта "Запчасти"  
письмо будет отправлено на user2@gmail.com

и так далее.

Пока удается только в шаблоне email.tpl в зависимости от выбранного селекта указать нужный заголовок письма.
Но разделить отправку по разным получателям не получается.

**альтернатива:**

При запуске формы сначала запускать промежуточную страницу на которой происходит выбор (автомобили,запчасти, сервис) и в зависимости от результата запускать отдельный шаблон Uniform
но уж больно решение не красивое.

вдруг, есть иные варианты?

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Сейчас так сделать нельзя.

**Comment by VitArts** [comment]
А жаль, интересная тема была бы.

**Comment by pafnuty** [comment]
@tcse @VitArts всё в ваших руках ✋ 
исх. код модуля то открыт :)

**Comment by tcse** [comment]
я, кстати ошибся :(

в email.tpl 

между тегами [header] и [/header]
вывод селектов не работает

другими словами такая запись
```
[header] Заказ звонка с сайта 
[uf_select_calltime="1_avto"]- про Автомобили[/uf_select_calltime]
[uf_select_calltime="2_pars"]- про Запчасти[/uf_select_calltime]
[uf_select_calltime="3_service"]- про Сервис[/uf_select_calltime]
[/header]
```

в реальном письме выводит сплошной текст

_Заказ звонка с сайта [uf_select_calltime="1_avto"]- про Автомобили[/uf_select_calltime]	[uf_select_calltime="2_pars"]- про Запчасти[/uf_select_calltime]	[uf_select_calltime="3_service"]- про Сервис[/uf_select_calltime]_ 


Но в теле письма без проблем отображает, что и ожидаемо.

**Comment by VitArts** [comment]
На самом деле да, если сделать, что бы темы письма были из селектов, то фильтрами в почте можно раскидывать письма куда хочешь.

**Comment by pafnuty** [comment]
@tcse какое это имеет отношение к теме тиккета?

**Comment by tcse** [comment]
@pafnuty как это какое?
прямое - описал альтернативный вариант в первом топике, предположив, что из шаблона email.tpl уж точно работает - но фигу :(
живой тест показал, что не работает из заголовка письма.
Вероятно так даже и не планировалось.
Или это просто баг?

**Comment by tcse** [comment]
@VitArts почтовыми фильтрами и сейчас легко раскидать.

если в тегах тегах сообщения прописать например так

```
<h2 style="margin: 0; padding: 20px; color: #ffffff; background: #164194;">
Заказ звонка с сайта
[uf_select_calltime="1_avto"]- про Автомобили[/uf_select_calltime]
[uf_select_calltime="2_pars"]- про Запчасти[/uf_select_calltime]
[uf_select_calltime="3_service"]- про Сервис[/uf_select_calltime]
</h2>
```
дальше уже фильтр по письму: Если сообщение содержит текст З**аказ звонка с сайта - про Запчасти** переместить письмо в папку....

**Comment by pafnuty** [comment]
@tcse тема тиккета: "Выбор получателя письма в зависимости от селекта в форме". 
То, что ты описал - баг (который ещё следует воспроизвести) и он не имеет **вообще** никакого отношения к фичам, которых нет в модуле :smile:

**Comment by tcse** [comment]
@pafnuty не поверишь... есть такое понятие как контекст.
И все написанное именно в контексте топика.

Но раз считаешь нужным разделять мух от котлет - дели.
Лишь бы результат был.

А про модификации на благо моих интересов сам знаешь - за мной не заржавеет. Расчет в начале месяца за прошедший. :)

**Comment by pafnuty** [comment]
Думаю этот вопрос можно закрыть реализовав https://github.com/dle-modules/DLE-UniForm/issues/40
