### ISSUE TITLE
передача в модуль содержимого дополнительных полей новости

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-UniForm#52]
Стоит ли ожидать в будущих версиях?

Что-бы в шаблон email.tpl передавались данные из [xfvalue_x] 

в form.tpl тоже бы не мешало. 

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@tcse Сейчас можно это делать через скрытые поля.
