### ISSUE TITLE
Не работает проверка чекбокса

### ISSUE THREAD

**Issue by ganniebal** [dle-modules/DLE-UniForm#53]
Помогите пожалуйста.
Нужно сделать обязательный чекбокс в инлайн форме - типа согалсен с договором. 
Если не ставлю галочку то ошибка выходит в таком виде 
[uf_error_checkbox1]
You must to accept TERMS & CONDITIONS
[/uf_error_checkbox1] Никак не могу сделать так чтобы в ошибке н ебыло этих тегов а только текст
те выводит теги на страницу. 
Если галочку ставлю то все в порядке.

В form где ошибки пишу так 
[uf_error_checkbox1]
<li>You must to accept TERMS & CONDITIONS</li>
[/uf_error_checkbox1]

В самой форме вывожу так:
<input type="checkbox" name="checkbox1" value="oneCheck" [uf_checkbox_checkbox1_oneCheck]checked[/uf_checkbox_checkbox1_oneCheck]> I agree with the Terms & Conditions</a>

конфиг: 
required = email,name,checkbox1
...
checkboxFields = checkbox1
---
А также вопрос - форма обратного звонка, на которой чекбокс является обязательным, отправляется с любым положением чекбокса.

@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-UniForm/issues/55
