### ISSUE TITLE
Uniform

### ISSUE THREAD

**Issue by ANDYkiller555** [dle-modules/DLE-UniForm#57]
Добрый день !
Прошу помочь, установлен на сайте модуль в трех местах  разными вариантами, после заполнения полей пишет, что все "ок", но письма не приходят на почту. Сайт http://vector-security.ru

**Comment by ANDYkiller555** [comment]
В папках theme/uniform/ , в config.tpl везде проставил почту

**Comment by pafnuty** [comment]
@ANDYkiller555 Проверьте отправляется ли обычная почта.
Проверьте папку спам.
Проверьте логи почтового сервера.
