### ISSUE TITLE
Вывод в form.tpl названия новости

### ISSUE THREAD

**Issue by al-voytik** [dle-modules/DLE-UniForm#59]
Здравствуйте, подскажите как вывести в form.tpl заголовок новости? 
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@al-voytik Ещё в версии 1,2 была реализована возможность отправлять в письме данные из новости. Для этого необходимо передать в форму поле newsId. Пример шаблона в папке **newsauthor**. В шаблоне email-сообщения можно использовать следующие теги:
`[news_id]{news_id}[/news_id] `— ID новости.
`[news_autor]{news_autor}[/news_autor]` — Логин автора.
`[news_title]{news_title}[/news_title]` — Заголовок новости.
`[news_email]{news_email}[/news_email]` — Email автора.

**Comment by al-voytik** [comment]
С письмом все предельно понятно, однако есть необходимость вывести название новости в саму форму обычным текстом. Вот там как раз этим способом и не получается вывести.

**Comment by pafnuty** [comment]
Используйте js для этих целей.
