### ISSUE TITLE
Пример формы запроса на удаление контента

### ISSUE THREAD

**Issue by pafnuty** [dle-modules/DLE-UniForm#6]
с 1 мая это актуально.

**Comment by tcse** [comment]
добавлю свои мысли о полезных полях в такой форме:

*скрытые поля*
- url страницы с которой была отправлена жалоба на контент {full-link}
- если это не аноним (а например специально зарегистрированный аккаунт) то login пользователя отправившего запрос


*поля для заполнения*
- email тут все ясно
- select: заявка на удаление файла, оскорбление чувств верующих, порно, разжигание розни,
- select: указать от лица какой организации наезд: правообладатель, адвокат, частное лицо
- указать название фирмы или человека который заявку оставляет.
- поле textarea 

*текст для уведомления об успешной отправки*

что-то типа правовой оговорки

а) Мы оставляем за собой право публикации на сайте любой информации присланной нам по почте.
б) Мы не осуществляем контроль за действиями пользователей, которые могут повторно размещать ссылки на информацию, являющуюся объектом вашего авторского права. Любая информация на сайте, размещается автоматически, без какого либо контроля с чьей либо стороны, что соответствует общепринятой мировой практике размещения информации в сети интернет. Однако, мы в любом случае рассмотрим все Ваши запросы, относительно ссылок на информацию, нарушающую Ваши права.

**Comment by pafnuty** [comment]
@tcse спасибо!

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-UniForm/releases/tag/v1.1
