### ISSUE TITLE
Работает через раз formConfig

### ISSUE THREAD

**Issue by aluckyanov** [dle-modules/DLE-UniForm#60]
Работает через раз "tarif": "Купить пост на канале". То на почте нормально всё
Ваше имя: ferferferf 
Услуга: Купить пост на канале

Потом начинается такое:
Ваше имя: fsdgsshhr
Услуга: {tarif}

`
 <a class="button b-color"  data-uf-open="/engine/ajax/uniform/uniform.php" data-uf-settings='{"formConfig": "feedback", "fields":{"tarif": "Купить пост на канале {news-id} telegram {title}"}}'>Купить пост</a>`

```
[header]
	[not_to_sender]
		Обращение из формы обратной связи
	[/not_to_sender]
	[to_sender]
		Ваше обращение из формы обратной связи
	[/to_sender]
[/header]
<h2 style="margin: 0; padding: 20px; color: #ffffff; background: #4b9fc5;">
[not_to_sender]
	Новое сообщение из формы обратной связи
[/not_to_sender]
[to_sender]
	Копия Вашего сообщения из формы обратной связи
[/to_sender]
</h2><div style="background: #fafafa; padding: 20px; color: #333333;">
	[not_to_sender]
		<b>email: </b> {email} <br>
		<b>Текст сообщения: </b> <br>
	[/not_to_sender]
	[to_sender]
		<b>Вам отправлена копия Вашего обращения: </b> <br>
	[/to_sender]
	
	<b>Ваше имя:</b> {textarea} <br><b>Услуга:</b> {tarif} </div>
```

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Что прописано в конфигурации формы?
Где можно посмотреть работу этой формы?

18 нояб. 2017 г. 10:52 ПП пользователь "aluckyanov" <
notifications@github.com> написал:

**Comment by aluckyanov** [comment]
https://for24.ru/bot/telegram/me/

"НАШИ ПАРТНЁРСКИЕ АККАУНТЫ" - там 4 разных формы

Конфигурация:

```
templateFolder = feedback
// nocache = y
// debug = y
required = textarea, email
// hidden = newsid,user
sendmail = y
sendToSender = y 
hidden = tarif 
emails = support@for24.ru
```

**Comment by tcse** [comment]
Павел, а я тебе говорил, что у меня такой-же баг с формами, а ты похоже не поверил. 
Может то с DLE 12.0 такая фигня? 

Перманентно пропадает обработка полей в email. Или как-то связано с количеством получателей письма (например, первым 2 отсылает как надо, а далее уже косячит)

**Comment by pafnuty** [comment]
@aluckyanov @tcse к сожалению у меня не воспроизводится ошибка (как и говорил ранее)
Возможно необходимо реализовать логирование всего, что происходит и наблюдать за тем, какие данные приезжают, как обрабатываются при разных ситуациях, чтобы понять где притаился баг.
Но у меня на это совершенно нет времени.

**Comment by aluckyanov** [comment]
@pafnuty возможно потому что я сделал другую кодировку модуля и при перекодировке что-то начинает слетать. Хотя перекодировал все файлы и теперь наоборот через раз такое.

**Comment by aluckyanov** [comment]
@pafnuty Поставил сейчас на чистый движок. Также проблема. Мб дело в версии php хостинга? Какие версии поддерживают hidden?

**Comment by pafnuty** [comment]
@aluckyanov без логирования, боюсь остаётся только гадать.
