### ISSUE TITLE
Перестала работать после переноса на https://

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#61]
Приветствую, перенес модуль на сайт с https:// форма выдает ошибку:
`Parse error: syntax error, unexpected '[' in /home/username/domains/site.ru/public_html/engine/ajax/uniform/uniform.php on line 43`

Подскажите, пожалуйста, как исправить?
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
У вас старая версия php.
