### ISSUE TITLE
E-mail пользователя в сообщении

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#64]
Привет, есть возможность сделать так, чтобы введенный пользователем e-mail появлялся в письме в "От кого"?
![default](https://user-images.githubusercontent.com/16765830/38254214-60125db2-3761-11e8-9b82-7b78d85b3d63.PNG)

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@inweid такой возможности нет и по логике не нужно т.к. во-первых это резко повышает шансы на попадание в спам, а во-вторых невозможно контролировать корректность email-адреса, с которого произошла отправка письма.
