### ISSUE TITLE
ошибка при нажатие "Отправить"

### ISSUE THREAD

**Issue by aluckyanov** [dle-modules/DLE-UniForm#65]
Установил модуль. После заполнения всех полей и нажатие на кнопку "Отправить" переходит на страницу https://site.ru/engine/ajax/uniform/uniform.php , где висит надпись "error".

Как можно решить данную проблему? 
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Устраните js ошибки.

ср, 2 мая 2018 г., 23:23 aluckyanov <notifications@github.com>:
