### ISSUE TITLE
Вопрос по модулю УниФорм

### ISSUE THREAD

**Issue by dollar1981** [dle-modules/DLE-UniForm#68]
---Добрый день Павел. У меня вопрос по вашему модулю. Кстати огромное вам спасибо за него! Он спасает меня постоянно.
Но вот есть небольшая незадача: Вывожу форму статично, на странице. Все отправляет, все работает. Но после отправки форма сворачивается и чтобы она развернулась снова, необходимо обновить страницу.
Нельзя ли как то сделать, чтобы допустим через 5 сек. форма сама снова разворачивалась?
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@dollar1981 да, конечно можно!
вот после этой строки https://github.com/dle-modules/DLE-UniForm/blob/master/templates/Default/uniform/js/uniform.js#L64 добавьте
```js
function reloadUniForm (selector) {
	var $this = $(selector),
		url = $this.data('ufInline'),
		data = $this.data('ufSettings');

	$.ajax({
			url: url,
			data: data,
		})
		.done(function (data) {
			$this.html(data);
		});
}
```
а после этой https://github.com/dle-modules/DLE-UniForm/blob/master/templates/Default/uniform/js/uniform.js#L73
```js
setTimeout(function () {
	reloadUniForm('.yourInlineForm')
}, 5000);
```

ну или что-то наподобие.
Суть в том, что бы после успешной отправки формы вызвать её загрузку снова, через некоторое время.

**Comment by pafnuty** [comment]
@dollar1981 добавьте к блоку с параметрами формы класс, который будете передавать в функцию. (ну или другой селектор)
В DLE уже есть библиотека jquery, нет необходимости подключать её отдельно.

**Comment by dollar1981** [comment]
Мда. Я ничего если честно не понял. 
Если не затруднит, можно поподробнее?

**Comment by pafnuty** [comment]
блок с параметрами формы: 
```html
<div data-uf-inline="/engine/ajax/uniform/uniform.php" data-uf-settings='{"formConfig": "inline"}'>
	<div class="uf-inline-loading"></div>
</div>
```
[jquery селектор](http://jquery.page2page.ru/index.php5/Селекторы)
Функция и её вызов описаны выше

**Comment by dollar1981** [comment]
И куда что вставить то? Я вставил в этот блок `'{"formConfig": "inline"}'` вызов своей формы, а именно callback. Она вывелась. Она работает. Но не открывается снова после отправки. Только если обновить страницу.

**Comment by dollar1981** [comment]
Или мне сюда его надо прописать `function reloadUniForm (selector) {
	var $this = $(selector),
		url = $this.data('ufInline'),
		data = $this.data('ufSettings');` ???

**Comment by dollar1981** [comment]
Типа `$this.data('ufcallback')`

**Comment by dollar1981** [comment]
Сейчас мой uniform.js выглядит так:

`var doc = $(document);

doc
	// ajax-отправка формы + эффекты
	.on('submit', '[data-uf-form]', function () {
		var $this = $(this),
			laddaLoad,
			options = {
				beforeSubmit: ufStart,
				success: ufDone,
			};

		$this.ajaxSubmit(options);

		return false;
	})
	// Открытие ajax-окна с формой
	.on('click', '[data-uf-open]', function (e) {
		var $this = $(this),
			src = $this.data('ufOpen'),
			data = $this.data('ufSettings');

		$.magnificPopup.open({
			items: {
				src: src,
			},
			focus: '.uf-input-first',
			type: 'ajax',
			ajax: {
				settings: {
					data: data
				}
			}
		});
		return false;
	})
	// Убираем класс с из инпута с ошибочным заполнением
	.on('keyup input', '.uf-input-error', function (e) {
		var $this = $(this);
		if (e.type == 'input') {
			doc.off('keyup', '.uf-input-error');
		}
		if ($this.val().length) {
			$this.removeClass('uf-input-error');
		}
	});


// Функция, выполняемая перед отправкой формы
function ufStart(formData, jqForm) {
	laddaLoad = jqForm.find('.ladda-button').ladda();
	laddaLoad.ladda('start');

	return true;
}

function reloadUniForm (selector) {
	var $this = $(selector),
		url = $this.data('ufInline'),
		data = $this.data('ufSettings');

	$.ajax({
			url: url,
			data: data,
		})
		.done(function (data) {
			$this.html(data);
		});
}

// Функция, выполняемая после удачной отправки формы
function ufDone(responseText, statusText, xhr, $form) {

	var $responseText = $(responseText),
		responseResult = ($responseText.is('form')) ? $responseText.html() : responseText;

	if (statusText == 'success') {
		laddaLoad.ladda('stop');
		$form.html(responseResult);
		setTimeout(function () {
	    reloadUniForm('.callback')
        }, 5000);
	}
}

jQuery(document).ready(function ($) {
	var $inlineUniform = $('[data-uf-inline]');
	if ($inlineUniform.length) {
		$.each($inlineUniform, function (index, val) {
			var $this = $(this),
				url = $this.data('ufInline'),
				data = $this.data('ufSettings');

			$.ajax({
					url: url,
					data: data,
				})
				.done(function (data) {
					$this.html(data);
				});

		});
	};
});`

**Comment by dollar1981** [comment]
Ткните носом пожалуйста меня.)))

**Comment by VitArts** [comment]
Смотрите, делаете все как написано выше по файлу (uniform.js).
Далее присваиваете класс форме откуда идет вызов формы, а именно:

` <div **class="yourInlineForm"** data-uf-inline="/engine/ajax/uniform/uniform.php" data-uf-settings='{"formConfig": "callback"}'>`

Все!
