### ISSUE TITLE
Не приходят письма

### ISSUE THREAD

**Issue by serg91100** [dle-modules/DLE-UniForm#7]
Не отправляются письма. Использовал 3 разных ящика. Никуда не упало

**Comment by pafnuty** [comment]
@serg91100 Как выглядит конфиг, как выглядит строка вызова модуля?

**Comment by serg91100** [comment]
Конфиг:

// -----------------
// Настройки UniForm
// -----------------

// -------------------------------------------
// Доступные параметры (значение по умолчанию)
// templateFolder — Папка с шаблонами формы формы, указывается подпапка, в папке uniform текущего шаблона сайта сайта (feedback), в которой должны лежать файлы config.tpl, form.tpl и email.tpl
// nocache        — Отключение кеширования модуля (false)
// debug          — Дебаг (false)
// required       — Обязательные поля (false)
// hidden         — Разрешенные скрытые поля (false). Такие поля передаются из data-* атрибута кнопки открытия формы
// sendmail       — Отправлять email при заполнения формы? (false)
// emails         — Адреса почты, на которые необходимо отправлять уведомление (false)
// selectFields   — Поля типа select
// checkboxFields — Поля типа checkbox
// radioFields    — Поля типа radio
// -------------------------------------------


templateFolder = feedback
// nocache = y
// debug = y
required = textarea, phone
// hidden = newsid,user
sendmail = y
// emails = serg91100@gmail.com

**Comment by serg91100** [comment]
Форма:

{* 
	Для вывода кнопки открытия формы используем код:
	<span data-uf-open="/engine/ajax/uniform/uniform.php" data-uf-settings='{"formConfig": "feedback"}' class="uf-btn">Задать вопрос</span> 
*}
<div class="uf-wrapper">
	<span class="mfp-close">&times;</span>
	<div class="uf-header">
		Обратная связь
	</div>
	[debug]<div class="uf-content">{debug}</div>[/debug]
	[error]
		<div class="uf-alert uf-alert-error">
			<b>Ошибка</b>
			<ul>
				[uf_token_error]
					<li>Ошибка сессии, попробуйте ещё раз.</li>
				[/uf_token_error]
				[uf_error_textarea]
					<li>Вы не написали сообщение</li>
				[/uf_error_textarea]					
				[uf_error_phone]
					<li>Вы не указали номер телефона</li>
				[/uf_error_phone]
			</ul>
		</div>
	[/error]
	[success]
		<div class="uf-content"><b>Спасибо за обращение!</b> <br> Если оно потребует ответа — мы свяжемся с вами</div>
	[/success]
	[form]
		
		<div class="uf-content">		
				<div class="uf-field">
				<div class="uf-label">
					Ваш телефон
				</div>
				<div class="uf-field-input">
					<input class="uf-input uf-input-first [uf_error_phone]uf-input-error[/uf_error_phone]" type="text" name="phone" value="{uf_field_phone}">
				</div>
			</div>
			<div class="uf-field">
				<div class="uf-label">
					Сообщение
				</div>
				<div class="uf-field-input">
					<textarea class="uf-input [uf_error_textarea]uf-input-error[/uf_error_textarea]" name="textarea" cols="30" rows="10">{uf_field_textarea}</textarea>
				</div>
			</div>
			<div class="uf-field">
				<div class="uf-label">
					&nbsp;
				</div>
				<div class="uf-field-input">
					<button class="uf-btn ladda-button" type="submit" data-style="zoom-out"><span class="ladda-label">Отправить</span></button>
				</div>
			</div>
		</div>
	[/form]
</div>

**Comment by serg91100** [comment]
Строка подключения:
<span style="float:right;" class="uf-btn" data-uf-open="/engine/ajax/uniform/uniform.php" data-uf-settings='{"formConfig": "feedback"}'>Обратная связь</span>

**Comment by pafnuty** [comment]
`// emails = serg91100@gmail.com`
уберите комментарий в начале строки.
в будущем используйте синтаксис [markdown](https://guides.github.com/features/mastering-markdown/) для оформления текста.
к примеру код надо закдючать вот в такую конструкцию:
```
	```
	тут код
	```
```

**Comment by serg91100** [comment]
Ой, дурак. Не увидел. Спасибо!

**Comment by serg91100** [comment]
Теперь другая ошибка - Ошибка сессии, попробуйте ещё раз. Я ничего не менял.

**Comment by pafnuty** [comment]
Просто отправьте форму ещё раз.

**Comment by serg91100** [comment]
Обновляет кнопку, ошибка не исчезает и не отправляется письмо.

**Comment by serg91100** [comment]
Под админом форма работает с ошибкой. Под гостем все нормально.

**Comment by pafnuty** [comment]
адрес сайта?

29 мая 2015 г., 10:14 пользователь serg91100 <notifications@github.com>
написал:

**Comment by serg91100** [comment]
http://test.webcoon.ru/vopros-otvet.html

**Comment by pafnuty** [comment]
Токен генерируется тут: https://github.com/dle-modules/DLE-UniForm/blob/master/upload/engine/modules/uniform/uniform.php#L254
для его генерации используется имя кеша, текущий шаблон сайта (из конфига) и id сессии. Если что-то не совпадает - выдаст ошибку.
