### ISSUE TITLE
Не работает прикрепить файл в версии 10.4. 

### ISSUE THREAD

**Issue by Sleedmx** [dle-modules/DLE-UniForm#70]
На странице установлен модуль - http://konstantinovka.biz/raspisanie/273-gorodskoe-raspisanie.html Устанавливал модуль на чистую 11.2 все работает, вложения приходят на почту. Скачал чистую установку 10.4 установил как тест на сайт http://dobrodecor.com, так же не работает вложение постоянно крутится. В console появляется ошибка - Uncaught Error: Syntax error, unrecognized expression: Fatal error: Call to undefined method dle_mail::addAttachment() in /engine/modules/uniform/sendmail.php on line 243. Без вложений модуль работает.  Как с этим бороться я не знаю( . За ранее Спасибо!

**Comment by pafnuty** [comment]
@Sleedmx в версии 10,4 нет возможности отправлять файлы.
