### ISSUE TITLE
Почему мне не приходят письма ?!

### ISSUE THREAD

**Issue by UtopiaEH** [dle-modules/DLE-UniForm#72]
---
Почему мне не приходят письма сайт andronilex.md console праверял конфиг настройн 

@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@UtopiaEH проверьте:
1) логи почтового сервера
2) папку спам на почте

**Comment by UtopiaEH** [comment]
папка спам чиста а логи хз как проверить пробовал перезалить файлы модуля не помогло

**Comment by UtopiaEH** [comment]
😞

**Comment by pafnuty** [comment]
по поводу просмотра логов обратитесь к хостеру.

**Comment by UtopiaEH** [comment]
[log.zip](https://github.com/dle-modules/DLE-UniForm/files/2162456/log.zip)

**Comment by pafnuty** [comment]
@UtopiaEH это логи вебсервера, а нужны логи почтового сервера.
