### ISSUE TITLE
Применение скриптов в инлайн форме

### ISSUE THREAD

**Issue by inweid** [dle-modules/DLE-UniForm#75]
Приветствую, как применить коллбэк после того, как на странице появится инлайн-форма?
Проблема в том, что не отрабатывают скрипты, которые применяются к инлайн-форме, поскольку она динамически появляется после формирования DOM.

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-UniForm/blob/master/templates/Default/uniform/js/uniform.js#L90
вот тут оторисоввывается html формы.
ниже можете написать код, который должен выполниться для неё.
