### ISSUE TITLE
Как можно реализовать проверку валидности вводимого телефона и почтового адреса?

### ISSUE THREAD

**Issue by saym101** [dle-modules/DLE-UniForm#77]
Приветствую. Как можно реализовать проверку валидности вводимого телефона и почтового адреса? И добавить в поле телефона шаблон вводимого номера?
Благодарю.
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@saym101 есть два варианта.
1) Использовать соответсвующите типы инпутов (phone и email)
2) Добавить плагин, реализующий валидацию.

Ну и ещё для верности, добавить проверку на стороне php модуля.

Про маски ввода можно посмотреть тут: https://github.com/dle-modules/DLE-UniForm/issues/49
