### ISSUE TITLE
абракадабра на емейл приходит.

### ISSUE THREAD

**Issue by andreichsb** [dle-modules/DLE-UniForm#79]
доброго времени. 
1 после установки приходит на мыло сообщение в другой кодировке. автокодер в инете говорит что приходит в ср1251. как исправить? 
2 как вообще устанавливается? - какая форма выводится, мне например нужно анкету сделать - куда более предметно посмотреть? (в программинге - только с книжкой)
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
@andreichsb 
1)  В какой кодировке у вас работает сайт? адрес сайта есть?
2) Вы можете посмотреть в документацию к модулю (на сайте) и в готовые примеры в существующих шаблонах модуля. Этого достаточно в большинстве случаев для реализации задуманного.

**Comment by andreichsb** [comment]
Павел приветствую.
1 вин1251
2 я не правильно сформулировал вопрос: то что готовых примеров в нем куча я понял - как происходит переключение между готовыми формами?

**Comment by pafnuty** [comment]
@andreichsb  Вам нужно либо сконвертировать файлы модуля в win1251 либо сконвертировать сайт в utf8
В каждом шаблоне есть form.tpl, в котором есть строка подключения для этого шаблона (в начале файла)

**Comment by andreichsb** [comment]
ну, наверное проще модуль в вин1251? а как сделать, не подскажете?

**Comment by andreichsb** [comment]
или может быть как то можно в модуле указать что бы отправляло в вин1251?

**Comment by pafnuty** [comment]
@andreichsb простой вариант - сконвертировать модуль.
Но в перспективе я бы рекомендовал двиг в utf-8
в качестве локального вебсервера используйте openServer https://ospanel.io/

**Comment by pafnuty** [comment]
@andreichsb то, что был выбор кодировки - просто интерфейс над перекодировкой контента на лету или не перекодировкой в зависимости от выбора.
Дистрибутив был всегда в 1251 и только относительно недавно стали делать файлы в нужной кодировке.
Сейчас кодировка по умолчанию - utf8, именно она рекомендуется (спустя лет 5 как это должно было стать нормой) для установки.
