### ISSUE TITLE
Проблема с чекбоксами

### ISSUE THREAD

**Issue by melsmakmer** [dle-modules/DLE-UniForm#8]
Если пользователь выбрал 3 чекбокса из 5-ти, и на почту пришли все пять причём выбранные три отображаются, а оставшиеся два приходят {тегом}

Может я что-то не так делаю...?

код шаблона email.tpl
----------------------------------------------
- {checkbox1}
- {checkbox2}
- {checkbox3}
- {checkbox4}
- {checkbox5}

Письмо с почты
---------------------------------------------
- Позиция 1
- Позиция 2
- Позиция 3
- {checkbox4}
- {checkbox5}

**Comment by pafnuty** [comment]
используйте так:
```
[uf_checkbox_checkbox1="value_x"]{checkbox1}[/uf_checkbox_checkbox1]
[uf_checkbox_checkbox2="value_x"]{checkbox2}[/uf_checkbox_checkbox2]
[uf_checkbox_checkbox3="value_x"]{checkbox3}[/uf_checkbox_checkbox3]
[uf_checkbox_checkbox4="value_x"]{checkbox4}[/uf_checkbox_checkbox4]
[uf_checkbox_checkbox5="value_x"]{checkbox5}[/uf_checkbox_checkbox5]
```
в следующей версии постараюсь решить проблему.

**Comment by melsmakmer** [comment]
к сожалению это не помогло..., теперь в обоях случаях не приходит  на почту независимо от того выбранный/не выбраный чекбокс

**Comment by pafnuty** [comment]
@melsmakmer а как выглядит сам шаблон формы?

**Comment by melsmakmer** [comment]
```
<label><input type="checkbox" name="checkbox1" value="Позиция 1">Позиция 1</label>
<label><input type="checkbox" name="checkbox2" value="Позиция 2">Позиция 2</label>
<label><input type="checkbox" name="checkbox3" value="Позиция 3">Позиция 3</label>
<label><input type="checkbox" name="checkbox4" value="Позиция 4">Позиция 4</label>
<label><input type="checkbox" name="checkbox5" value="Позиция 5">Позиция 5</label>
```

**Comment by pafnuty** [comment]
```
[uf_checkbox_checkbox1="Позиция 1"]{checkbox1}[/uf_checkbox_checkbox1]
[uf_checkbox_checkbox2="Позиция 2"]{checkbox2}[/uf_checkbox_checkbox2]
...
```

**Comment by melsmakmer** [comment]
пробывал... не приходит на почту вообще независимо от того выбранный/не выбраный чекбокс

**Comment by pafnuty** [comment]
Пропишите value у чекбоксов на латинице и проверку поправьте.
 20.06.2015 13:43 пользователь "Mels" <notifications@github.com> написал:

**Comment by melsmakmer** [comment]
Спасибо, это помогло решить проблему, всё отлично работает! Получается причина, value не поддерживает кирилицу..
email.tpl
-------------------------------
[uf_checkbox_position1="position1"] Выбрана позиция 1 [/uf_checkbox_position1]

вот только так, {тэгом} уже не вставишь...

**Comment by pafnuty** [comment]
Ну писать value на кириллице в селектах,  чекбоксах и радиокнопках и не
принято,  хотя странно,  что кириллица не срабатывает.
20.06.2015 16:37 пользователь "Mels" <notifications@github.com> написал:
