### ISSUE TITLE
Перестал работать модуль

### ISSUE THREAD

**Issue by never3d22** [dle-modules/DLE-UniForm#81]
---
@pafnuty не забудь посмотреть этот тиккет :ticket:
привет
https://pafnuty.name/modules/page,1,24,159-uniform.html
config file not found
ничего не трогал, но перестал работать

**Comment by pafnuty** [comment]
@never3d22 
- Проверьте наличие файла конфига
- Проверьте корректность строки вызова модуля в шаблоне
- Проверьте корректность шаблонов, которые используются модулем для вывода данной формы.
