### ISSUE TITLE
помогите пожалуйста с юниформ)

### ISSUE THREAD

**Issue by Ustim86** [dle-modules/DLE-UniForm#84]
---
@pafnuty не забудь посмотреть этот тиккет :ticket:
Здравствуйте, писал Вам с почты гмейл, но там какая то ошибка. Продублирую отсюда. У меня два одинаковых сайта, просто на разных доменах. С одной формы сообщения отправляются хорошо. А другая пишет ошибку:  [uf_error_textarea]
Будьте добры, помогите разобраться)
Вот содержимое файла фидбэк/конфиг.тпл
 templateFolder = feedback
// nocache = y
// debug = y
required = textarea, email, name, phone
// hidden = newsid,user
sendmail = y
emails = evgeniy.dryaev@yandex.com

а вот фидбэк/форм.тпл
<script src='https://www.google.com/recaptcha/api.js'></script>

[debug]<div class="uf-content">{debug}</div>[/debug]
[error]
<div class="uf-alert uf-alert-error">
    <b>Ошибка</b>
    <ul>
        [uf_token_error]
            <li>Ошибка сессии, попробуйте ещё раз.</li>
        [/uf_token_error]
        [uf_error_textarea]
            <li>Вы не написали сообщение</li>
        [/uf_error_textarea]
        [uf_error_email]
            <li>Вы не указали email</li>
        [/uf_error_email]
        [uf_error_phone]
            <li>Вы не указали телефон</li>
        [/uf_error_phone]
        [uf_email_error]
            <li>Проверьте правильность ввода email</li>
        [/uf_email_error]
        [uf_recaptcha_error]
        <li>Подтвердите, что Вы не робот</li>
        [/uf_recaptcha_error]
    </ul>
</div>
[/error]
[success]
<div class="uf-content"><b>Спасибо за обращение!</b> <br> Если оно потребует ответа — мы свяжемся с вами</div>
[/success]
[form]
<div class="row">
<div class="col-md-4">
<div class="form-group">
<label>Ваше ФИО</label>
<input type="text" class="form-control required" name="name" placeholder="Иванов Иван Иванович">
</div>
</div>
<div class="col-md-4">
<div class="form-group">
<label>E-mail</label>
<input type="text" class="form-control required [uf_error_email]uf-input-error[/uf_error_email] [uf_email_error]uf-input-error[/uf_email_error]" name="email" placeholder="name@mail.ru" value="{uf_field_email}">
</div>
</div>
<div class="col-md-4">
<div class="form-group">
<label>Телефон:</label>
<input type="text" class="form-control required [uf_error_phone]uf-input-error[/uf_error_phone] [uf_phone_error]uf-input-error[/uf_phone_error]" name="phone" placeholder="+7(000)000-00-00">
</div>
</div>
<div class="col-md-12">
<div class="form-group">
<label>Текст сообщения:</label>
<textarea type="text" class="form-control required [uf_error_textarea]uf-input-error[/uf_error_textarea]" name="textarea" placeholder="Введите текст">{uf_field_textarea}</textarea>
</div>
</div>

<div class="col-md-12">
    <div class="g-recaptcha" data-sitekey="6Lf8eJcUAAAAAHL2wnQ4SwHTe-UIzahCSYyks-kf"></div>
</div>

<div class="col-md-12"><button class="uf-btn ladda-button" type="submit" data-style="zoom-in"><span class="ladda-label">Отправить</span></button></div>
</div>
[/form]

**Comment by pafnuty** [comment]
@Ustim86 Если два одинаковых сайта с одинаковыми настройками, одинаковыми модулями - проблема точно не в модуле.
Возможно проблема похожа на https://github.com/dle-modules/DLE-UniForm/issues/66
пробовали отключать кеш?

**Comment by Ustim86** [comment]
Мне уже сделали, скорее всего так и было. Смотрю что уже отключено, спасибо)
