### ISSUE TITLE
Дополнительные поля в форме

### ISSUE THREAD

**Issue by Ustim86** [dle-modules/DLE-UniForm#86]
Здравствуйте. Вот ставлю Вашу форму на сайт http://www.div-blockpost.ru с кнопкой слева "Заказать игру" И открывается обычный шаблон "feedback" в котором просто две строки "Укажите е-mail" и "Напишите сообщение"
А у меня владелец сайта просит чтобы была форма типа:
Ваш телефон*:
Дополнительная информация об игре:
Выберите дату:
Сколько игроков:
На какое время:
Вид игры:

Как добавить ещё эти произвольные поля чтобы было правильно?)

**Comment by pafnuty** [comment]
@Ustim86 в шаблоне https://github.com/dle-modules/DLE-UniForm/blob/master/templates/Default/uniform/test/form.tpl вы можете найти различные примеры готовых полей.
