### ISSUE TITLE
Перезагрузка статической формы

### ISSUE THREAD

**Issue by dollar1981** [dle-modules/DLE-UniForm#87]
---
@pafnuty не забудь посмотреть этот тиккет :ticket:
Еще вопрос: Вставил форму не в модальное окно, а вывел прямо на странице сайта, после отправки появляется сообщение об успешной отправке и все! То есть чтобы форма снова появилась надо перезагружать страницу, а можно как то сделать автоматом? Чтобы после успешной отправке, форма сама перезагружалась? И что необходимо для этого сделать?

**Comment by VitArts** [comment]
в файле uniform.js добавить ` location.reload();`  после

 ```
if (statusText == 'success') {
		laddaLoad.ladda('stop');
		$form.html(responseResult);
	}
```

Но это самое элементарное, если нужно перезагружать только на одной какой-то форме то надо выполнять проверку (если эта форма то выполняем код)
