### ISSUE TITLE
Размер кнопки заказа

### ISSUE THREAD

**Issue by Ustim86** [dle-modules/DLE-UniForm#88]
Здравствуйте. Смотрю инспектором что кнопка у нас на сайте: http://div-blockpost.ru в коде как .uf-btn
Но там нету не одной настройки которая отвечала бы за размер. Есть размер шрифта, но когда я его меняю в коде то на сайте ничего не меняется)
 Как то кнопку нужно побольше сделать...

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Пропишите 
```css 
font: 400 14px/40px Arial, sans-serif
```
у вас там вместо `normal` написано `norml`

**Comment by Ustim86** [comment]
менял на normal и прописывал так font: 400 14px/40px Arial, sans-serif
и всё равно не реагирует..)

**Comment by pafnuty** [comment]
Что-то вы делаете не так.
Проверяйте кеш, проверяйте доступ к файлу на запись, проверяйте тот ли файл правите.
![2019-05-31_22-35-33](https://user-images.githubusercontent.com/1635679/58727110-79c93880-83f4-11e9-809c-60cf251ab7bc.gif)

**Comment by Ustim86** [comment]
А у меня оно здесь почему то перечёркнуто...
http://div-blockpost.ru/uploads/Screenshot_37.png

**Comment by Ustim86** [comment]
Всё, понятно. В конце ж точка с запятой не стоит: font: normal 14px/40px Arial, sans-serif
))

**Comment by Ustim86** [comment]
Чтобы не открывать новый тикет. Была украинская почта в коде:
templateFolder = callback
// nocache = y
// debug = y
required = phone, 
required = textarea, email, header
selectFields = calltime
sendmail = y
emails = ustim@3g.ua

Всё приходит отлично.
Меняем на мейл.ру либо Яндекс.ру и не приходит) Там есть какой то секрет?
