### ISSUE TITLE
Проблемы с отправкой на mail.ru

### ISSUE THREAD

**Issue by pafnuty** [dle-modules/DLE-UniForm#89]
Чтобы не открывать новый тикет. Была украинская почта в коде:
templateFolder = callback
// nocache = y
// debug = y
required = phone, 
required = textarea, email, header
selectFields = calltime
sendmail = y
emails = ustim@3g.ua

Всё приходит отлично.
Меняем на мейл.ру либо Яндекс.ру и не приходит) Там есть какой то секрет?

_Originally posted by @Ustim86 in https://github.com/dle-modules/DLE-UniForm/issues/88#issuecomment-499269317_

**Comment by pafnuty** [comment]
@Ustim86 Лучше на каждый вопрос создавать новое обращение, что бы другие пользователи могли быстрее найти ответ на свой вопрос в будущем.

Скорее всего проблема в том, что отправка письма происходит с адреса, не соответствующего домену.
т.е. ваш домен site.com, а письмо отправляется с admin@othersite.com
Попробуете настроить корректную отправку писем либо используйте например https://connect.yandex.ru/pdd/

**Comment by Ustim86** [comment]
Там с яндекс коннектом куча мороки привязывать. И хочется на свою почту чтобы шли письма. Уже выставил везде почту что на mail.ru заканчивается либо на gmail.com и всё равно не приходит...
на украинскую i.ua - приходит мгновенно.
