### ISSUE TITLE
Помогите пожалуйста с Uniform

### ISSUE THREAD

**Issue by kap4kman** [dle-modules/DLE-UniForm#95]
Здравствуйте, можете помочь мне в решении вопросов с Uniform? Не приходят письма ни с какой страницы))) Отправка все работает, а на почту не приходят, перепробовал все что мог. Спасибо большое. Сайт: audiomax.kz
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Небольшой FAQ [есть тут](https://pafnuty.name/modules/159-uniform.html#faq)

[Q]: Не приходит письмо.
[A]: Проверьте конфиг модуля (поле emails должно быть раскомментировано). Если всё ок — проверьте папку спам (недопочты типа mail.ru, rambler и прочие noname почтовые службы очень часто при неправильной настройке сервера отправляют письма в спам, особенно, если у вас shared-хостинг). Если в папке спам ничего нет — проверьте логи почтового сервера (узнать о расположении логов можно у хостера). Самый простой способ избежать конфузов при отправке почты - подключить [почту для домена](https://connect.yandex.ru/pdd/).
